#!/usr/bin/env python3
"""
Regenerates Figures 1, 3, and 4 of the report from committed CSVs (Figure 2
is generated by Step3_calibration/fit_k_delta.py directly, since it's tightly
coupled to that fit). Run from the figures/ directory; all paths below are
relative to it.

Figure 1 -- metal-to-semiconductor failure: PBE gap (exactly 0 at delta=0,
every lattice length, from DFT_bgap.csv) vs. a cheap illustrative periodic
HF scan (Step3_calibration/fig1_hf_delta_scan.csv) that does NOT close the
gap at delta=0. Motivates keeping the PBE-based beta(r) shape rather than
replacing it with an HF-derived one.

Figure 3 -- corrected gap curve: at the 8 calibration geometries (equilibrium
ridge, l and delta increasing together), the original TB/PBE-fit gap, the
k_inf-rescaled gap, and the actual EOM-CCSD extrapolated ab initio gap,
all vs. delta. A delta=0 anchor point (gap=0 for both TB curves, by
construction) is added to make the preserved metal-to-semiconductor
transition visually explicit.

Figure 4 -- exciton binding energy convergence: binding_energy_eV vs.
1/natoms for the three methods compared in Step 2 (Koopmans+CIS baseline,
EOM-CCSD fundamental + CIS optical, CAM-B3LYP TDDFT optical), one plot.
"""

import csv
import numpy as np
import matplotlib.pyplot as plt

STEP2 = '../Step2'
STEP3 = '../Step3_calibration'


def read_csv(path):
    with open(path, newline='') as f:
        return list(csv.DictReader(f))


def read_dft_bgap_row(path, lattice_length):
    with open(path) as f:
        lines = f.readlines()
    header = lines[0].strip().split(',')
    deltas_grid = [float(x) for x in header[1:]]
    for line in lines[1:]:
        parts = line.strip().split(None, 1)
        if not parts:
            continue
        l = float(parts[0])
        if abs(l - lattice_length) < 1e-6:
            vals = [float(x) for x in parts[1].split(',')]
            return deltas_grid, vals
    raise ValueError(f"lattice_length {lattice_length} not found in {path}")


def fig1():
    hf_rows = read_csv(f'{STEP3}/fig1_hf_delta_scan.csv')
    hf_rows.sort(key=lambda r: float(r['delta']))
    hf_delta = [float(r['delta']) for r in hf_rows]
    hf_gap = [float(r['indirect_gap_eV']) for r in hf_rows]

    # Real PBE curve at the same lattice length (l=6.0), interpolated onto
    # the HF scan's delta points from the full DFT_bgap.csv grid -- NOT a
    # flat zero line; PBE's gap does open with delta, it just starts at
    # exactly 0 at delta=0 (the point being illustrated), unlike HF.
    deltas_grid, vals_grid = read_dft_bgap_row(f'{STEP3}/DFT_bgap.csv', 6.0)
    pbe_delta = hf_delta
    pbe_gap = list(np.interp(hf_delta, deltas_grid, vals_grid))

    fig, ax = plt.subplots(figsize=(6, 4.5))
    ax.plot(pbe_delta, pbe_gap, 'o-', color='tab:green', label='PBE (Quantum ESPRESSO)')
    ax.plot(hf_delta, hf_gap, 'o-', color='tab:red',
             label='periodic HF (illustrative, nk=4/vacuum=15A)')
    ax.set_xlabel('dimerization, delta')
    ax.set_ylabel('indirect band gap (eV)')
    ax.set_title('Metal-to-semiconductor transition: PBE vs. HF near delta=0')
    ax.legend(fontsize=9)
    fig.tight_layout()
    fig.savefig('../report/figures/fig1_metal_transition.png', dpi=200)
    print("Saved fig1_metal_transition.png")


def fig3():
    old_new = read_csv(f'{STEP3}/gap_old_vs_new.csv')
    old_new.sort(key=lambda r: float(r['delta']))
    delta = [float(r['delta']) for r in old_new]
    gap_old = [float(r['gap_old_eV']) for r in old_new]
    gap_new = [float(r['gap_new_eV']) for r in old_new]

    summary = read_csv(f'{STEP2}/beta_rescaling_k_summary.csv')
    summary.sort(key=lambda r: float(r['delta']))
    ab_delta = [float(r['delta']) for r in summary]
    ab_gap = [float(r['extrap_gap_largest4']) for r in summary]

    # delta=0 anchor: both TB curves vanish there by construction
    delta_plot = [0.0] + delta
    gap_old_plot = [0.0] + gap_old
    gap_new_plot = [0.0] + gap_new

    fig, ax = plt.subplots(figsize=(6.5, 5))
    ax.plot(delta_plot, gap_old_plot, '--', color='tab:blue', marker='o', markersize=4,
             label='TB model, original beta(r) (PBE-fit)')
    ax.plot(delta_plot, gap_new_plot, '-', color='tab:purple', marker='o', markersize=4,
             label='TB model, rescaled beta(r) (k_inf applied)')
    ax.scatter(ab_delta, ab_gap, color='black', marker='x', s=60, zorder=5,
               label='EOM-CCSD extrapolated ab initio gap')
    ax.set_xlabel('dimerization, delta')
    ax.set_ylabel('fundamental gap (eV)')
    ax.set_title('Corrected gap curve along the equilibrium ridge\n'
                  '(both TB curves vanish at delta=0 by construction)')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig('../report/figures/fig3_corrected_gap_curve.png', dpi=200)
    print("Saved fig3_corrected_gap_curve.png")


def fig4():
    koopmans = read_csv(f'{STEP2}/exciton_binding_convergence.csv')
    eom = read_csv(f'{STEP2}/exciton_binding_eom_ccsd.csv')
    lc = read_csv(f'{STEP2}/exciton_binding_lc_tddft.csv')

    def series(rows, key='binding_energy_eV'):
        rows = sorted(rows, key=lambda r: int(r['natoms']))
        x = [1.0 / int(r['natoms']) for r in rows]
        y = [float(r[key]) for r in rows]
        return x, y

    fig, ax = plt.subplots(figsize=(6.5, 5))
    for rows, label, color in [
        (koopmans, 'Koopmans + CIS (baseline)', 'tab:blue'),
        (eom, 'EOM-CCSD fundamental + CIS optical', 'tab:orange'),
        (lc, 'Koopmans fundamental + CAM-B3LYP optical', 'tab:green'),
    ]:
        x, y = series(rows)
        ax.plot(x, y, 'o-', color=color, label=label)

    ax.set_xlabel('1 / natoms')
    ax.set_ylabel('exciton binding energy (eV)')
    ax.set_title('Exciton binding energy: finite-size convergence by method')
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig('../report/figures/fig4_binding_energy_convergence.png', dpi=200)
    print("Saved fig4_binding_energy_convergence.png")


if __name__ == '__main__':
    fig1()
    fig3()
    fig4()
