# Import statements required for a single bath 
from math import ceil
import os
import json as json
import numpy as np
from tqdm import tqdm
from tenso.prototypes.bath import gen_bcf
# Import statements required for multiple baths (needed later)
from math import ceil
from tenso.prototypes.heom import system_multibath
from tenso.prototypes.default_parameters import quantity
# Import statement required to plot results
import matplotlib.pyplot as plt

# Generate the bath correlation function and decompose
# it for HEOM propagation
bath_simulation = gen_bcf(
    re_d=[540], 
    width_d=[70], 
    freq_b=[1243],
    re_b=[161.6],
    width_b=[10],
    temperature=300, 
    decomposition_method='Pade',
    n_ltc=1,) 
end_time = 500 # Propagation time in fs
dt = 1 # Time step size in fs
wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
out="two_baths" # Base name for the output

bath_op1 = np.array([[-0.5,0.0],[0.0,0.5]],dtype=np.complex128)
bath_op2 = np.array([[0.0,0.5],[0.5,0.0]],dtype=np.complex128)

# Generate the propagator that will advance the system
propagator = system_multibath( 
    fname=out, # Specify output file
    init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
    sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
    sys_ops=[bath_op1,bath_op2], # Set the H_{SB} system-bath coupling operator (cm^{-1})
    bath_correlations=[bath_simulation, bath_simulation], # Specify a bath correlation function generated by gen_bcf
    dim=30, # Hierarchy depth
    end_time=end_time, # End time of the simulation
    step_time=dt,) # Time step size
# Perform the dynamics simulation and generate a progress bar 
progress_bar = tqdm(propagator,total=ceil(end_time/dt))
for _t in progress_bar:
    progress_bar.set_description(f'@{_t: .2f} fs')
    
# Load results from the output file into a local array
results = np.loadtxt(out+".dat.log",dtype=np.complex128)
# Plot the populations of the two state of the spin-boson problem
plt.plot(np.real(results[:,0]),np.real(results[:,1]),np.real(results[:,0]),np.real(results[:,4]))
plt.xlabel("Time (fs)")
plt.ylabel("Population")
plt.savefig(out+'.png')
plt.show()
